### ISSUE TITLE
Return an image file instead of yt plot object

### ISSUE THREAD

**Issue by samwalkow** [data-exp-lab/analysis_schema#31]
### Description

Currently, a list of yt objects is returned from the rendering engine. Those objects are then visualized and also saved as images in the local directory. We should change this so it just returns the image files.

**Comment by chrishavlin** [comment]
This one was completed in #21 ! but I think we should keep this issue open until #26 is complete since those examples might need modification. The change in #21 does allow the yt plot html encoding to be returned -- so the jupyter notebooks couple be updated to use display(html) or we could add a little jupyter-wrapper to display the plots as html.

**Comment by chrishavlin** [comment]
this one's ok to close now since #26 is closed.
